/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CerebrumFHEVM_v09 {
  export type EligibilityCheckStruct = {
    lender: AddressLike;
    minScore: BigNumberish;
    timestamp: BigNumberish;
    amountPaid: BigNumberish;
  };

  export type EligibilityCheckStructOutput = [
    lender: string,
    minScore: bigint,
    timestamp: bigint,
    amountPaid: bigint
  ] & {
    lender: string;
    minScore: bigint;
    timestamp: bigint;
    amountPaid: bigint;
  };

  export type ActivityLogStruct = {
    action: string;
    timestamp: BigNumberish;
    blockNumber: BigNumberish;
  };

  export type ActivityLogStructOutput = [
    action: string,
    timestamp: bigint,
    blockNumber: bigint
  ] & { action: string; timestamp: bigint; blockNumber: bigint };
}

export interface CerebrumFHEVM_v09Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_DATA_SHARE_REWARD"
      | "BASE_RESEARCHER_FEE"
      | "INITIAL_SCORE"
      | "LENDER_CHECK_FEE"
      | "MAX_SCORE"
      | "PLATFORM_FEE_PERCENT"
      | "SCORE_INCREMENT"
      | "TIER_COMPLETE"
      | "TIER_PREMIUM"
      | "TIER_STANDARD"
      | "approveLender"
      | "calculateAccessPrice"
      | "calculateComprehensiveRisk"
      | "checkEligibility"
      | "checkEligibilityWithEncryptedThreshold"
      | "claimEarnings"
      | "eligibilityHistory"
      | "getApprovedPatients"
      | "getEligibilityHistory"
      | "getEncryptedEligibilityResult"
      | "getEncryptedHealthRecord"
      | "getEncryptedHealthScore"
      | "getEncryptedRiskScores"
      | "getHealthRecordCount"
      | "getHealthRecordMetadata"
      | "getPatientActivity"
      | "getPatientInfo"
      | "getPatientList"
      | "getRecordQuality"
      | "getResearcherPurchaseCount"
      | "getResearcherPurchasedPatients"
      | "getSharingEnabledCount"
      | "getSharingEnabledPatients"
      | "getTotalDataShares"
      | "getTotalPatients"
      | "hasCurrentAccess"
      | "hasLenderApproval"
      | "hasResearcherAccess"
      | "isPatientRegistered"
      | "isSharingEnabled"
      | "lenderApprovals"
      | "owner"
      | "patients"
      | "platformWallet"
      | "protocolId"
      | "purchaseResearcherAccess"
      | "registerPatient"
      | "researcherAccessRound"
      | "researcherRiskScores"
      | "revokeLender"
      | "riskScoringLibrary"
      | "setPlatformWallet"
      | "setRiskScoringLibrary"
      | "shareHealthData"
      | "toggleDataSharing"
      | "totalDataShares"
      | "totalPatients"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DataSharingToggled"
      | "DebugHandles"
      | "EarningsDistributed"
      | "EligibilityChecked"
      | "EligibilityPermissionGranted"
      | "HealthDataPermissionGranted"
      | "HealthDataShared"
      | "LenderApprovalGranted"
      | "LenderApprovalRevoked"
      | "PatientRegistered"
      | "ResearcherAccessGranted"
      | "ResearcherAccessPurchased"
      | "RiskScoresCalculated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_DATA_SHARE_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_RESEARCHER_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LENDER_CHECK_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_SCORE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCORE_INCREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_COMPLETE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_PREMIUM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_STANDARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveLender",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateAccessPrice",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateComprehensiveRisk",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkEligibility",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkEligibilityWithEncryptedThreshold",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eligibilityHistory",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApprovedPatients",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEligibilityHistory",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedEligibilityResult",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedHealthRecord",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedHealthScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedRiskScores",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthRecordCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthRecordMetadata",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientActivity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordQuality",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResearcherPurchaseCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResearcherPurchasedPatients",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSharingEnabledCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSharingEnabledPatients",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDataShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPatients",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasCurrentAccess",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasLenderApproval",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasResearcherAccess",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPatientRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSharingEnabled",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lenderApprovals",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "patients",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseResearcherAccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPatient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "researcherAccessRound",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "researcherRiskScores",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeLender",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "riskScoringLibrary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskScoringLibrary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shareHealthData",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleDataSharing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDataShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPatients",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_DATA_SHARE_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_RESEARCHER_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LENDER_CHECK_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SCORE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCORE_INCREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_COMPLETE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_PREMIUM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_STANDARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveLender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateAccessPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateComprehensiveRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkEligibilityWithEncryptedThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eligibilityHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApprovedPatients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEligibilityHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedEligibilityResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedHealthRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedHealthScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedRiskScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHealthRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHealthRecordMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordQuality",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResearcherPurchaseCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResearcherPurchasedPatients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSharingEnabledCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSharingEnabledPatients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDataShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPatients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCurrentAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasLenderApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasResearcherAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPatientRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSharingEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lenderApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "patients", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseResearcherAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "researcherAccessRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "researcherRiskScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeLender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskScoringLibrary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskScoringLibrary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shareHealthData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleDataSharing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDataShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPatients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DataSharingToggledEvent {
  export type InputTuple = [
    patient: AddressLike,
    enabled: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    enabled: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    enabled: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugHandlesEvent {
  export type InputTuple = [
    storedHealthScoreHandle: BytesLike,
    minScoreHandle: BytesLike,
    resultHandle: BytesLike
  ];
  export type OutputTuple = [
    storedHealthScoreHandle: string,
    minScoreHandle: string,
    resultHandle: string
  ];
  export interface OutputObject {
    storedHealthScoreHandle: string;
    minScoreHandle: string;
    resultHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsDistributedEvent {
  export type InputTuple = [
    patient: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EligibilityCheckedEvent {
  export type InputTuple = [
    patient: AddressLike,
    lender: AddressLike,
    minScore: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    lender: string,
    minScore: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    lender: string;
    minScore: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EligibilityPermissionGrantedEvent {
  export type InputTuple = [
    patient: AddressLike,
    lender: AddressLike,
    resultHandle: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    lender: string,
    resultHandle: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    lender: string;
    resultHandle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HealthDataPermissionGrantedEvent {
  export type InputTuple = [
    patient: AddressLike,
    researcher: AddressLike,
    recordIndex: BigNumberish,
    bloodSugarHandle: BytesLike,
    cholesterolHandle: BytesLike,
    bmiHandle: BytesLike,
    bpSystolicHandle: BytesLike,
    bpDiastolicHandle: BytesLike,
    heartRateHandle: BytesLike,
    weightHandle: BytesLike,
    heightHandle: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    researcher: string,
    recordIndex: bigint,
    bloodSugarHandle: string,
    cholesterolHandle: string,
    bmiHandle: string,
    bpSystolicHandle: string,
    bpDiastolicHandle: string,
    heartRateHandle: string,
    weightHandle: string,
    heightHandle: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    researcher: string;
    recordIndex: bigint;
    bloodSugarHandle: string;
    cholesterolHandle: string;
    bmiHandle: string;
    bpSystolicHandle: string;
    bpDiastolicHandle: string;
    heartRateHandle: string;
    weightHandle: string;
    heightHandle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HealthDataSharedEvent {
  export type InputTuple = [
    patient: AddressLike,
    timestamp: BigNumberish,
    recordNumber: BigNumberish,
    qualityScore: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    timestamp: bigint,
    recordNumber: bigint,
    qualityScore: bigint
  ];
  export interface OutputObject {
    patient: string;
    timestamp: bigint;
    recordNumber: bigint;
    qualityScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LenderApprovalGrantedEvent {
  export type InputTuple = [
    patient: AddressLike,
    lender: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    lender: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    lender: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LenderApprovalRevokedEvent {
  export type InputTuple = [
    patient: AddressLike,
    lender: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    lender: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    lender: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientRegisteredEvent {
  export type InputTuple = [patient: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [patient: string, timestamp: bigint];
  export interface OutputObject {
    patient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResearcherAccessGrantedEvent {
  export type InputTuple = [
    patient: AddressLike,
    researcher: AddressLike,
    dataVersion: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    researcher: string,
    dataVersion: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    researcher: string;
    dataVersion: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResearcherAccessPurchasedEvent {
  export type InputTuple = [
    patient: AddressLike,
    researcher: AddressLike,
    price: BigNumberish,
    patientPayment: BigNumberish,
    platformFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    researcher: string,
    price: bigint,
    patientPayment: bigint,
    platformFee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    researcher: string;
    price: bigint;
    patientPayment: bigint;
    platformFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskScoresCalculatedEvent {
  export type InputTuple = [
    patient: AddressLike,
    researcher: AddressLike,
    recordIndex: BigNumberish,
    diabetesHandle: BytesLike,
    heartHandle: BytesLike,
    strokeHandle: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    researcher: string,
    recordIndex: bigint,
    diabetesHandle: string,
    heartHandle: string,
    strokeHandle: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    researcher: string;
    recordIndex: bigint;
    diabetesHandle: string;
    heartHandle: string;
    strokeHandle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CerebrumFHEVM_v09 extends BaseContract {
  connect(runner?: ContractRunner | null): CerebrumFHEVM_v09;
  waitForDeployment(): Promise<this>;

  interface: CerebrumFHEVM_v09Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_DATA_SHARE_REWARD: TypedContractMethod<[], [bigint], "view">;

  BASE_RESEARCHER_FEE: TypedContractMethod<[], [bigint], "view">;

  INITIAL_SCORE: TypedContractMethod<[], [bigint], "view">;

  LENDER_CHECK_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  SCORE_INCREMENT: TypedContractMethod<[], [bigint], "view">;

  TIER_COMPLETE: TypedContractMethod<[], [bigint], "view">;

  TIER_PREMIUM: TypedContractMethod<[], [bigint], "view">;

  TIER_STANDARD: TypedContractMethod<[], [bigint], "view">;

  approveLender: TypedContractMethod<
    [lender: AddressLike],
    [void],
    "nonpayable"
  >;

  calculateAccessPrice: TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [bigint],
    "view"
  >;

  calculateComprehensiveRisk: TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [
      [string, string, string] & {
        diabetesRisk: string;
        heartRisk: string;
        strokeRisk: string;
      }
    ],
    "nonpayable"
  >;

  checkEligibility: TypedContractMethod<
    [patient: AddressLike, minCreditScore: BigNumberish],
    [void],
    "payable"
  >;

  checkEligibilityWithEncryptedThreshold: TypedContractMethod<
    [patient: AddressLike, encryptedMinScore: BytesLike, inputProof: BytesLike],
    [void],
    "payable"
  >;

  claimEarnings: TypedContractMethod<[], [void], "nonpayable">;

  eligibilityHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        lender: string;
        minScore: bigint;
        timestamp: bigint;
        amountPaid: bigint;
      }
    ],
    "view"
  >;

  getApprovedPatients: TypedContractMethod<
    [lender: AddressLike],
    [string[]],
    "view"
  >;

  getEligibilityHistory: TypedContractMethod<
    [patient: AddressLike, lender: AddressLike],
    [CerebrumFHEVM_v09.EligibilityCheckStructOutput[]],
    "view"
  >;

  getEncryptedEligibilityResult: TypedContractMethod<
    [patient: AddressLike],
    [string],
    "nonpayable"
  >;

  getEncryptedHealthRecord: TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [
      [string, string, string, string, string, string, string, string] & {
        bloodSugar: string;
        cholesterol: string;
        bmi: string;
        bloodPressureSystolic: string;
        bloodPressureDiastolic: string;
        heartRate: string;
        weight: string;
        height: string;
      }
    ],
    "nonpayable"
  >;

  getEncryptedHealthScore: TypedContractMethod<
    [patient: AddressLike],
    [string],
    "view"
  >;

  getEncryptedRiskScores: TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [
      [string, string, string] & {
        diabetesRisk: string;
        heartDiseaseRisk: string;
        strokeRisk: string;
      }
    ],
    "nonpayable"
  >;

  getHealthRecordCount: TypedContractMethod<
    [_patient: AddressLike],
    [bigint],
    "view"
  >;

  getHealthRecordMetadata: TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        age: bigint;
        exerciseMinutes: bigint;
        sleepHours: bigint;
        timestamp: bigint;
        qualityScore: bigint;
      }
    ],
    "view"
  >;

  getPatientActivity: TypedContractMethod<
    [_patient: AddressLike],
    [CerebrumFHEVM_v09.ActivityLogStructOutput[]],
    "view"
  >;

  getPatientInfo: TypedContractMethod<
    [_patient: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, bigint] & {
        isRegistered: boolean;
        sharingEnabled: boolean;
        lastDataShare: bigint;
        registrationTime: bigint;
        dataShareCount: bigint;
        totalEarnings: bigint;
      }
    ],
    "view"
  >;

  getPatientList: TypedContractMethod<[], [string[]], "view">;

  getRecordQuality: TypedContractMethod<
    [_patient: AddressLike, recordIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getResearcherPurchaseCount: TypedContractMethod<
    [researcher: AddressLike],
    [bigint],
    "view"
  >;

  getResearcherPurchasedPatients: TypedContractMethod<
    [researcher: AddressLike],
    [string[]],
    "view"
  >;

  getSharingEnabledCount: TypedContractMethod<[], [bigint], "view">;

  getSharingEnabledPatients: TypedContractMethod<[], [string[]], "view">;

  getTotalDataShares: TypedContractMethod<[], [bigint], "view">;

  getTotalPatients: TypedContractMethod<[], [bigint], "view">;

  hasCurrentAccess: TypedContractMethod<
    [patient: AddressLike, researcher: AddressLike],
    [boolean],
    "view"
  >;

  hasLenderApproval: TypedContractMethod<
    [patient: AddressLike, lender: AddressLike],
    [boolean],
    "view"
  >;

  hasResearcherAccess: TypedContractMethod<
    [patient: AddressLike, researcher: AddressLike],
    [boolean],
    "view"
  >;

  isPatientRegistered: TypedContractMethod<
    [_patient: AddressLike],
    [boolean],
    "view"
  >;

  isSharingEnabled: TypedContractMethod<
    [_patient: AddressLike],
    [boolean],
    "view"
  >;

  lenderApprovals: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  patients: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, string, bigint, bigint, bigint, bigint] & {
        isRegistered: boolean;
        sharingEnabled: boolean;
        healthScore: string;
        lastDataShare: bigint;
        registrationTime: bigint;
        dataShareCount: bigint;
        totalEarnings: bigint;
      }
    ],
    "view"
  >;

  platformWallet: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  purchaseResearcherAccess: TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [void],
    "payable"
  >;

  registerPatient: TypedContractMethod<[], [void], "nonpayable">;

  researcherAccessRound: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  researcherRiskScores: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [
      [string, string, string, bigint] & {
        diabetesRisk: string;
        heartDiseaseRisk: string;
        strokeRisk: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  revokeLender: TypedContractMethod<
    [lender: AddressLike],
    [void],
    "nonpayable"
  >;

  riskScoringLibrary: TypedContractMethod<[], [string], "view">;

  setPlatformWallet: TypedContractMethod<
    [_platformWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setRiskScoringLibrary: TypedContractMethod<
    [_riskScoringLibrary: AddressLike],
    [void],
    "nonpayable"
  >;

  shareHealthData: TypedContractMethod<
    [
      encBloodSugar: BytesLike,
      encCholesterol: BytesLike,
      encBmi: BytesLike,
      encBpSystolic: BytesLike,
      encBpDiastolic: BytesLike,
      encHeartRate: BytesLike,
      encWeight: BytesLike,
      encHeight: BytesLike,
      age: BigNumberish,
      exerciseMinutes: BigNumberish,
      sleepHours: BigNumberish,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  toggleDataSharing: TypedContractMethod<[], [void], "nonpayable">;

  totalDataShares: TypedContractMethod<[], [bigint], "view">;

  totalPatients: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_DATA_SHARE_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_RESEARCHER_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LENDER_CHECK_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCORE_INCREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_COMPLETE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_PREMIUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_STANDARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveLender"
  ): TypedContractMethod<[lender: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateAccessPrice"
  ): TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateComprehensiveRisk"
  ): TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [
      [string, string, string] & {
        diabetesRisk: string;
        heartRisk: string;
        strokeRisk: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkEligibility"
  ): TypedContractMethod<
    [patient: AddressLike, minCreditScore: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "checkEligibilityWithEncryptedThreshold"
  ): TypedContractMethod<
    [patient: AddressLike, encryptedMinScore: BytesLike, inputProof: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "claimEarnings"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "eligibilityHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        lender: string;
        minScore: bigint;
        timestamp: bigint;
        amountPaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApprovedPatients"
  ): TypedContractMethod<[lender: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEligibilityHistory"
  ): TypedContractMethod<
    [patient: AddressLike, lender: AddressLike],
    [CerebrumFHEVM_v09.EligibilityCheckStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedEligibilityResult"
  ): TypedContractMethod<[patient: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedHealthRecord"
  ): TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [
      [string, string, string, string, string, string, string, string] & {
        bloodSugar: string;
        cholesterol: string;
        bmi: string;
        bloodPressureSystolic: string;
        bloodPressureDiastolic: string;
        heartRate: string;
        weight: string;
        height: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedHealthScore"
  ): TypedContractMethod<[patient: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedRiskScores"
  ): TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [
      [string, string, string] & {
        diabetesRisk: string;
        heartDiseaseRisk: string;
        strokeRisk: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getHealthRecordCount"
  ): TypedContractMethod<[_patient: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHealthRecordMetadata"
  ): TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        age: bigint;
        exerciseMinutes: bigint;
        sleepHours: bigint;
        timestamp: bigint;
        qualityScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPatientActivity"
  ): TypedContractMethod<
    [_patient: AddressLike],
    [CerebrumFHEVM_v09.ActivityLogStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPatientInfo"
  ): TypedContractMethod<
    [_patient: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, bigint] & {
        isRegistered: boolean;
        sharingEnabled: boolean;
        lastDataShare: bigint;
        registrationTime: bigint;
        dataShareCount: bigint;
        totalEarnings: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPatientList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecordQuality"
  ): TypedContractMethod<
    [_patient: AddressLike, recordIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResearcherPurchaseCount"
  ): TypedContractMethod<[researcher: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResearcherPurchasedPatients"
  ): TypedContractMethod<[researcher: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSharingEnabledCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSharingEnabledPatients"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalDataShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalPatients"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasCurrentAccess"
  ): TypedContractMethod<
    [patient: AddressLike, researcher: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasLenderApproval"
  ): TypedContractMethod<
    [patient: AddressLike, lender: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasResearcherAccess"
  ): TypedContractMethod<
    [patient: AddressLike, researcher: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPatientRegistered"
  ): TypedContractMethod<[_patient: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSharingEnabled"
  ): TypedContractMethod<[_patient: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lenderApprovals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "patients"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, string, bigint, bigint, bigint, bigint] & {
        isRegistered: boolean;
        sharingEnabled: boolean;
        healthScore: string;
        lastDataShare: bigint;
        registrationTime: bigint;
        dataShareCount: bigint;
        totalEarnings: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseResearcherAccess"
  ): TypedContractMethod<
    [patient: AddressLike, recordIndex: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registerPatient"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "researcherAccessRound"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "researcherRiskScores"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [
      [string, string, string, bigint] & {
        diabetesRisk: string;
        heartDiseaseRisk: string;
        strokeRisk: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeLender"
  ): TypedContractMethod<[lender: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "riskScoringLibrary"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPlatformWallet"
  ): TypedContractMethod<[_platformWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRiskScoringLibrary"
  ): TypedContractMethod<
    [_riskScoringLibrary: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shareHealthData"
  ): TypedContractMethod<
    [
      encBloodSugar: BytesLike,
      encCholesterol: BytesLike,
      encBmi: BytesLike,
      encBpSystolic: BytesLike,
      encBpDiastolic: BytesLike,
      encHeartRate: BytesLike,
      encWeight: BytesLike,
      encHeight: BytesLike,
      age: BigNumberish,
      exerciseMinutes: BigNumberish,
      sleepHours: BigNumberish,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "toggleDataSharing"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalDataShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPatients"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DataSharingToggled"
  ): TypedContractEvent<
    DataSharingToggledEvent.InputTuple,
    DataSharingToggledEvent.OutputTuple,
    DataSharingToggledEvent.OutputObject
  >;
  getEvent(
    key: "DebugHandles"
  ): TypedContractEvent<
    DebugHandlesEvent.InputTuple,
    DebugHandlesEvent.OutputTuple,
    DebugHandlesEvent.OutputObject
  >;
  getEvent(
    key: "EarningsDistributed"
  ): TypedContractEvent<
    EarningsDistributedEvent.InputTuple,
    EarningsDistributedEvent.OutputTuple,
    EarningsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "EligibilityChecked"
  ): TypedContractEvent<
    EligibilityCheckedEvent.InputTuple,
    EligibilityCheckedEvent.OutputTuple,
    EligibilityCheckedEvent.OutputObject
  >;
  getEvent(
    key: "EligibilityPermissionGranted"
  ): TypedContractEvent<
    EligibilityPermissionGrantedEvent.InputTuple,
    EligibilityPermissionGrantedEvent.OutputTuple,
    EligibilityPermissionGrantedEvent.OutputObject
  >;
  getEvent(
    key: "HealthDataPermissionGranted"
  ): TypedContractEvent<
    HealthDataPermissionGrantedEvent.InputTuple,
    HealthDataPermissionGrantedEvent.OutputTuple,
    HealthDataPermissionGrantedEvent.OutputObject
  >;
  getEvent(
    key: "HealthDataShared"
  ): TypedContractEvent<
    HealthDataSharedEvent.InputTuple,
    HealthDataSharedEvent.OutputTuple,
    HealthDataSharedEvent.OutputObject
  >;
  getEvent(
    key: "LenderApprovalGranted"
  ): TypedContractEvent<
    LenderApprovalGrantedEvent.InputTuple,
    LenderApprovalGrantedEvent.OutputTuple,
    LenderApprovalGrantedEvent.OutputObject
  >;
  getEvent(
    key: "LenderApprovalRevoked"
  ): TypedContractEvent<
    LenderApprovalRevokedEvent.InputTuple,
    LenderApprovalRevokedEvent.OutputTuple,
    LenderApprovalRevokedEvent.OutputObject
  >;
  getEvent(
    key: "PatientRegistered"
  ): TypedContractEvent<
    PatientRegisteredEvent.InputTuple,
    PatientRegisteredEvent.OutputTuple,
    PatientRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ResearcherAccessGranted"
  ): TypedContractEvent<
    ResearcherAccessGrantedEvent.InputTuple,
    ResearcherAccessGrantedEvent.OutputTuple,
    ResearcherAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ResearcherAccessPurchased"
  ): TypedContractEvent<
    ResearcherAccessPurchasedEvent.InputTuple,
    ResearcherAccessPurchasedEvent.OutputTuple,
    ResearcherAccessPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "RiskScoresCalculated"
  ): TypedContractEvent<
    RiskScoresCalculatedEvent.InputTuple,
    RiskScoresCalculatedEvent.OutputTuple,
    RiskScoresCalculatedEvent.OutputObject
  >;

  filters: {
    "DataSharingToggled(address,bool,uint256)": TypedContractEvent<
      DataSharingToggledEvent.InputTuple,
      DataSharingToggledEvent.OutputTuple,
      DataSharingToggledEvent.OutputObject
    >;
    DataSharingToggled: TypedContractEvent<
      DataSharingToggledEvent.InputTuple,
      DataSharingToggledEvent.OutputTuple,
      DataSharingToggledEvent.OutputObject
    >;

    "DebugHandles(bytes32,bytes32,bytes32)": TypedContractEvent<
      DebugHandlesEvent.InputTuple,
      DebugHandlesEvent.OutputTuple,
      DebugHandlesEvent.OutputObject
    >;
    DebugHandles: TypedContractEvent<
      DebugHandlesEvent.InputTuple,
      DebugHandlesEvent.OutputTuple,
      DebugHandlesEvent.OutputObject
    >;

    "EarningsDistributed(address,uint256,uint256)": TypedContractEvent<
      EarningsDistributedEvent.InputTuple,
      EarningsDistributedEvent.OutputTuple,
      EarningsDistributedEvent.OutputObject
    >;
    EarningsDistributed: TypedContractEvent<
      EarningsDistributedEvent.InputTuple,
      EarningsDistributedEvent.OutputTuple,
      EarningsDistributedEvent.OutputObject
    >;

    "EligibilityChecked(address,address,uint64,uint256)": TypedContractEvent<
      EligibilityCheckedEvent.InputTuple,
      EligibilityCheckedEvent.OutputTuple,
      EligibilityCheckedEvent.OutputObject
    >;
    EligibilityChecked: TypedContractEvent<
      EligibilityCheckedEvent.InputTuple,
      EligibilityCheckedEvent.OutputTuple,
      EligibilityCheckedEvent.OutputObject
    >;

    "EligibilityPermissionGranted(address,address,bytes32,uint256)": TypedContractEvent<
      EligibilityPermissionGrantedEvent.InputTuple,
      EligibilityPermissionGrantedEvent.OutputTuple,
      EligibilityPermissionGrantedEvent.OutputObject
    >;
    EligibilityPermissionGranted: TypedContractEvent<
      EligibilityPermissionGrantedEvent.InputTuple,
      EligibilityPermissionGrantedEvent.OutputTuple,
      EligibilityPermissionGrantedEvent.OutputObject
    >;

    "HealthDataPermissionGranted(address,address,uint256,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      HealthDataPermissionGrantedEvent.InputTuple,
      HealthDataPermissionGrantedEvent.OutputTuple,
      HealthDataPermissionGrantedEvent.OutputObject
    >;
    HealthDataPermissionGranted: TypedContractEvent<
      HealthDataPermissionGrantedEvent.InputTuple,
      HealthDataPermissionGrantedEvent.OutputTuple,
      HealthDataPermissionGrantedEvent.OutputObject
    >;

    "HealthDataShared(address,uint256,uint256,uint8)": TypedContractEvent<
      HealthDataSharedEvent.InputTuple,
      HealthDataSharedEvent.OutputTuple,
      HealthDataSharedEvent.OutputObject
    >;
    HealthDataShared: TypedContractEvent<
      HealthDataSharedEvent.InputTuple,
      HealthDataSharedEvent.OutputTuple,
      HealthDataSharedEvent.OutputObject
    >;

    "LenderApprovalGranted(address,address,uint256)": TypedContractEvent<
      LenderApprovalGrantedEvent.InputTuple,
      LenderApprovalGrantedEvent.OutputTuple,
      LenderApprovalGrantedEvent.OutputObject
    >;
    LenderApprovalGranted: TypedContractEvent<
      LenderApprovalGrantedEvent.InputTuple,
      LenderApprovalGrantedEvent.OutputTuple,
      LenderApprovalGrantedEvent.OutputObject
    >;

    "LenderApprovalRevoked(address,address,uint256)": TypedContractEvent<
      LenderApprovalRevokedEvent.InputTuple,
      LenderApprovalRevokedEvent.OutputTuple,
      LenderApprovalRevokedEvent.OutputObject
    >;
    LenderApprovalRevoked: TypedContractEvent<
      LenderApprovalRevokedEvent.InputTuple,
      LenderApprovalRevokedEvent.OutputTuple,
      LenderApprovalRevokedEvent.OutputObject
    >;

    "PatientRegistered(address,uint256)": TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;
    PatientRegistered: TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;

    "ResearcherAccessGranted(address,address,uint256,uint256)": TypedContractEvent<
      ResearcherAccessGrantedEvent.InputTuple,
      ResearcherAccessGrantedEvent.OutputTuple,
      ResearcherAccessGrantedEvent.OutputObject
    >;
    ResearcherAccessGranted: TypedContractEvent<
      ResearcherAccessGrantedEvent.InputTuple,
      ResearcherAccessGrantedEvent.OutputTuple,
      ResearcherAccessGrantedEvent.OutputObject
    >;

    "ResearcherAccessPurchased(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ResearcherAccessPurchasedEvent.InputTuple,
      ResearcherAccessPurchasedEvent.OutputTuple,
      ResearcherAccessPurchasedEvent.OutputObject
    >;
    ResearcherAccessPurchased: TypedContractEvent<
      ResearcherAccessPurchasedEvent.InputTuple,
      ResearcherAccessPurchasedEvent.OutputTuple,
      ResearcherAccessPurchasedEvent.OutputObject
    >;

    "RiskScoresCalculated(address,address,uint256,bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      RiskScoresCalculatedEvent.InputTuple,
      RiskScoresCalculatedEvent.OutputTuple,
      RiskScoresCalculatedEvent.OutputObject
    >;
    RiskScoresCalculated: TypedContractEvent<
      RiskScoresCalculatedEvent.InputTuple,
      RiskScoresCalculatedEvent.OutputTuple,
      RiskScoresCalculatedEvent.OutputObject
    >;
  };
}
