/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CerebrumRiskScoringInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateComprehensiveRisk"
      | "calculateDiabetesRisk"
      | "calculateHeartDiseaseRisk"
      | "calculateStrokeRisk"
      | "confidentialProtocolId"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateComprehensiveRisk",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateDiabetesRisk",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateHeartDiseaseRisk",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateStrokeRisk",
    values: [BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateComprehensiveRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateDiabetesRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateHeartDiseaseRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateStrokeRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
}

export interface CerebrumRiskScoring extends BaseContract {
  connect(runner?: ContractRunner | null): CerebrumRiskScoring;
  waitForDeployment(): Promise<this>;

  interface: CerebrumRiskScoringInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateComprehensiveRisk: TypedContractMethod<
    [
      bloodSugar: BytesLike,
      cholesterol: BytesLike,
      bmi: BytesLike,
      bloodPressureSystolic: BytesLike,
      heartRate: BytesLike,
      age: BigNumberish
    ],
    [
      [string, string, string] & {
        diabetesRisk: string;
        heartRisk: string;
        strokeRisk: string;
      }
    ],
    "nonpayable"
  >;

  calculateDiabetesRisk: TypedContractMethod<
    [bloodSugar: BytesLike, bmi: BytesLike, age: BigNumberish],
    [string],
    "nonpayable"
  >;

  calculateHeartDiseaseRisk: TypedContractMethod<
    [
      cholesterol: BytesLike,
      bloodPressureSystolic: BytesLike,
      heartRate: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  calculateStrokeRisk: TypedContractMethod<
    [
      bloodPressureSystolic: BytesLike,
      cholesterol: BytesLike,
      age: BigNumberish,
      bmi: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateComprehensiveRisk"
  ): TypedContractMethod<
    [
      bloodSugar: BytesLike,
      cholesterol: BytesLike,
      bmi: BytesLike,
      bloodPressureSystolic: BytesLike,
      heartRate: BytesLike,
      age: BigNumberish
    ],
    [
      [string, string, string] & {
        diabetesRisk: string;
        heartRisk: string;
        strokeRisk: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateDiabetesRisk"
  ): TypedContractMethod<
    [bloodSugar: BytesLike, bmi: BytesLike, age: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateHeartDiseaseRisk"
  ): TypedContractMethod<
    [
      cholesterol: BytesLike,
      bloodPressureSystolic: BytesLike,
      heartRate: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateStrokeRisk"
  ): TypedContractMethod<
    [
      bloodPressureSystolic: BytesLike,
      cholesterol: BytesLike,
      age: BigNumberish,
      bmi: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
