/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICerebrumRiskScoring,
  ICerebrumRiskScoringInterface,
} from "../../../contracts/CerebrumFHEVM_v09.sol/ICerebrumRiskScoring";

const _abi = [
  {
    inputs: [
      {
        internalType: "euint64",
        name: "bloodSugar",
        type: "bytes32",
      },
      {
        internalType: "euint64",
        name: "cholesterol",
        type: "bytes32",
      },
      {
        internalType: "euint64",
        name: "bmi",
        type: "bytes32",
      },
      {
        internalType: "euint64",
        name: "bloodPressureSystolic",
        type: "bytes32",
      },
      {
        internalType: "euint64",
        name: "heartRate",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "age",
        type: "uint8",
      },
    ],
    name: "calculateComprehensiveRisk",
    outputs: [
      {
        internalType: "euint64",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "euint64",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "euint64",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "euint64",
        name: "bloodSugar",
        type: "bytes32",
      },
      {
        internalType: "euint64",
        name: "bmi",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "age",
        type: "uint8",
      },
    ],
    name: "calculateDiabetesRisk",
    outputs: [
      {
        internalType: "euint64",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "euint64",
        name: "cholesterol",
        type: "bytes32",
      },
      {
        internalType: "euint64",
        name: "bloodPressureSystolic",
        type: "bytes32",
      },
      {
        internalType: "euint64",
        name: "heartRate",
        type: "bytes32",
      },
    ],
    name: "calculateHeartDiseaseRisk",
    outputs: [
      {
        internalType: "euint64",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "euint64",
        name: "bloodPressureSystolic",
        type: "bytes32",
      },
      {
        internalType: "euint64",
        name: "cholesterol",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "age",
        type: "uint8",
      },
      {
        internalType: "euint64",
        name: "bmi",
        type: "bytes32",
      },
    ],
    name: "calculateStrokeRisk",
    outputs: [
      {
        internalType: "euint64",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICerebrumRiskScoring__factory {
  static readonly abi = _abi;
  static createInterface(): ICerebrumRiskScoringInterface {
    return new Interface(_abi) as ICerebrumRiskScoringInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICerebrumRiskScoring {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICerebrumRiskScoring;
  }
}
